name: Nix

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: jwieringa-nixos-config
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check
      - run: nix build .#nixosConfigurations.vm-intel.config.system.build.toplevel
      - uses: actions/upload-artifact@v2
        with:
          name: vmware
          path: ./result/*.vmdk
